server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

            spring:
  application:
    name: api-gateway

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
