server:
  port: 8080

  spring:
  application:
    name: api-gateway

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # USER SERVICE ROUTE
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        # ORDER SERVICE ROUTE
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

