server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: Baan@786

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
