server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: Baan@786

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    spring:
  application:
    name: api-gateway

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
